### ISSUE TITLE
Fix prod assets to https (Fix Twitter Card and OG)

### ISSUE THREAD

**Issue by sungchoi** [dtothefp/build-boiler#18]
Hey @dtothefp,

The image on the twitter card for /commit is not showing up. OG debugger says that the image URL  is invalid, although it still manages to pick up the image. Douglas and I think that changing the protocol to be https would fix the problem. Not guaranteed of course.

Reference
https://github.com/dtothefp/build-boiler/blob/6011a3a75839239fbd882b6c21dda6807f5efc62/configs/boiler-config-hfa/src/index.js#L3

Do you think we can update this on build-boiler or should we just override it on commit only.

Sung

**Comment by dtothefp** [comment]
@sungchoi this actually isn't a `build-boiler` issue. look in the `boiler.config.js` and these configs come from https://github.com/HillaryClinton/boiler-config-hfa/blob/master/src/index.js. Look at the `extends` property. You can create your own locally similar to the link you showed above for the local extended config of `build-boiler`
